main: []

social:
  - identifier: bilibili
    name: Bilibili
    url: "https://space.bilibili.com/1859472020"
    params:
      icon: brand-bilibili
      weight: 1

  - identifier: github
    name: Github
    url: "https://github.com/zxyaow"
    params:
      icon: brand-github
      weight: 2

  - identifier: twitter
    name: Twitter
    url: "https://twitter.com/@_ziyao_"
    params:
      icon: brand-twitter
      weight: 3
